vikrambombhi/SimpleSurvey

pom.xml
src/main/java/com/example/survey/SurveyApplication.java
src/main/java/com/example/survey/models/OptionQuestion.java
src/main/java/com/example/survey/models/OptionQuestionRepo.java
src/main/java/com/example/survey/models/RangeQuestion.java
src/main/java/com/example/survey/models/RangeQuestionRepo.java
src/main/java/com/example/survey/models/Survey.java
src/main/java/com/example/survey/models/SurveyRepo.java
src/main/java/com/example/survey/models/TextQuestion.java
src/main/java/com/example/survey/models/TextQuestionRepo.java

Creates a basic model for all the questions and survey.
All the models need tests
I wanted to make an abstract Question class but couldnt figure out how to get it working with PS this might be something we want to investigate but its not nessary.

Base models

---

.travis.yml

@vikrambombhi I don't think I have permission to add this to travis, can you do it? Here's the file

travis + heroku integration

---

pom.xml

Couldn't compile it locally until I added this

add maven source and target

---

.gitignore
pom.xml
public/index.html
public/public.js
src/main/java/com/example/survey/models/SurveyController.java
src/main/java/com/example/survey/models/SurveyRepo.java

* Creates a SurveyController
* Add's https://github.com/Shopify/polaris-react CSS 
* Update SPA to fetch surveys from the API and lists it on the page
NOTES: 
- We'll need to add some tests for this controller
- I haven't styled the UI that comes from the "Add Question" button. 
- Submit isn't hooked up yet.

Add SurveyController and update SPA to pull in survey names

---

src/main/java/com/example/survey/models/RangeQuestion.java
src/test/java/com/example/survey/models/RangeQuestionTest.java

Tests for RangeQuestion

---

src/main/java/com/example/survey/models/OptionQuestion.java
src/test/java/com/example/survey/models/OptionQuestionTest.java

closes #17 
This PR adds tests for OptionQuestion and fixes some implementations

OptionQuestion Tests

---

public/index.html

changed route for favicon

---

public/index.html

This fixes issue #21 
Removed unused ID form part, and unused “submit” param.

rm unused param and ID form input

---

src/main/java/com/example/survey/models/SurveyController.java

Add API for adding survey

---

pom.xml
src/test/java/com/example/survey/SurveyApplicationTests.java

New survey test

---

public/index.html
src/main/java/com/example/survey/models/Survey.java
src/main/java/com/example/survey/models/SurveyController.java
src/main/java/com/example/survey/models/SurveyRepo.java
src/test/java/com/example/survey/SurveyApplicationTests.java

Re: #34
This PR sets the initial work to closing a survey.
1. Fixing consistency issues with field names in Survey and the type of the ID.
1. Setting up an endpoint for closing the survey.
1. Better test structure for JSON endpoints.
The next steps are to return the questions and their answers when closed.

First Steps To Closing Survey

---

src/main/java/com/example/survey/models/Answer.java
src/main/java/com/example/survey/models/Question.java
src/main/java/com/example/survey/models/RangeQuestion.java
src/test/java/com/example/survey/SurveyApplicationTests.java

blocked on #37 merging
closes #34 
This PR of close survey returns the list of answers per question. Tests also validate this.
If #37 isn't' merged yet, just review commits done by me. 
Next steps are to call the endpoint from the frontend

Close Survey

---

client/package.json
client/src/components/App.js
client/src/components/NewSurveyModal.js
client/src/components/SurveyList.js
client/src/components/index.js
client/src/components/pages/CompleteSurveys.js
client/src/components/pages/CreateSurveys.js
client/src/components/pages/Home.js
client/src/components/pages/index.js
client/src/setupTests.js
client/src/tests/App.test.js
client/src/tests/NewSurveyModal.test.js
client/yarn.lock
src/main/java/com/example/survey/models/SurveyController.java

Closes https://github.com/vikrambombhi/SimpleSurvey/issues/47
This PR adds: 
* `react-router-dom` to handle app navigations
* Adds pages to the app and navigations between these pages 
Next steps: 
- List the questions in the survey on the cards https://github.com/vikrambombhi/SimpleSurvey/issues/52
- `Complete Survey` link on cards should link to a page where users can complete surveys https://github.com/vikrambombhi/SimpleSurvey/issues/45
- `Edit Survey` link on admin cards should link to a page where uses can add questions to the survey

Setup app page navigation

---

client/src/components/NewSurveyModal.js
client/src/components/index.js
client/src/setupTests.js
client/src/tests/App.test.js
client/src/tests/NewSurveyModal.test.js
src/main/java/com/example/survey/models/SurveyController.java

Closes https://github.com/vikrambombhi/SimpleSurvey/issues/46
This PR: 
* Adds the form to create a new survey
* Updates the page with the new form created
* Adds tests for the client
**Modal:** 
**List updated:**

Finish new survey form

---

client/src/components/App.js
client/src/components/NewSurveyModal.js
client/src/components/SurveyList.js
client/src/components/pages/CompleteSurveys.js
client/src/components/pages/CreateSurveys.js
client/src/components/pages/Home.js
src/main/java/com/example/survey/models/SurveyController.java
src/main/java/com/example/survey/models/SurveyRepo.java
src/main/java/com/example/survey/models/WebConfiguration.java
src/main/resources/application.properties
src/test/java/com/example/survey/SurveyApplicationTests.java

Closes https://github.com/vikrambombhi/SimpleSurvey/issues/53
Verified locally by building production locally with the following. I'm confident this will work. 
```
$ mvn package
$ java -jar target/survey-0.0.1-SNAPSHOT.jar
```

Fix prod by splitting up api to /api and react to /app 

---

client/src/components/NewSurveyModal.js

Wait for form submit to complete before refreshing data

Fix form submit bug

---

src/main/java/com/example/survey/RestDataConfig.java
src/test/java/com/example/survey/SurveyApplicationTests.java

Include ids for frontend functionality

Include IDs on /api/surveys

---

client/src/components/SurveyList.js

Close Survey Frontend

---

client/src/components/QuestionList.js
client/src/components/SurveyForm.js
client/src/components/pages/NewSurvey.js

L7 FED
Spotlight uuuhhh moonlight uuhhh

Add questions when creating a survey

---

client/src/components/SurveyForm.js

undo regression

---

src/main/java/com/example/survey/controllers/QuestionController.java
src/main/java/com/example/survey/models/Answer.java
src/main/java/com/example/survey/models/QuestionRepo.java
src/test/java/com/example/survey/SurveyApplicationTests.java

backend for #45 
Question controller for answering questions.

Question Controller 

---

client/src/components/QuestionList.js
client/src/components/SurveyForm.js
client/src/components/pages/NewSurvey.js
client/src/tests/NewSurveyModal.test.js

closes #64 
This PR just fixes the frontend form. Does not fix submit of it.
I keep state in parents, and set it in children.
The state is an array of objects, the objects are questions with values like type, title, options, text, min, max.

More form states

---

client/src/components/QuestionList.js
client/src/components/SurveyForm.js
client/src/components/SurveyList.js
client/src/components/pages/NewSurvey.js
src/main/java/com/example/survey/SurveyApplication.java
src/main/java/com/example/survey/controllers/SurveyController.java
src/main/java/com/example/survey/models/Answer.java
src/main/java/com/example/survey/models/OptionQuestion.java
src/main/java/com/example/survey/models/Question.java
src/main/java/com/example/survey/models/RangeQuestion.java
src/main/java/com/example/survey/models/SurveyRepo.java
src/main/java/com/example/survey/models/TextQuestion.java
src/main/java/com/example/survey/models/TextQuestionRepo.java
src/test/java/com/example/survey/SurveyApplicationTests.java
src/test/java/com/example/survey/models/AnswerTest.java
src/test/java/com/example/survey/models/OptionQuestionTest.java
src/test/java/com/example/survey/models/QuestionTest.java
src/test/java/com/example/survey/models/RangeQuestionTest.java
src/test/java/com/example/survey/models/SurveyTest.java
src/test/java/com/example/survey/models/TextQuestionTest.java

I did a few things here:
* Added tests for json ser and deser
* Format the `options` on the form to be an array of strings, instead of a string with commas in it
* changed toStrings to not sort, instead I sort or call `containsString` in the tests
* removed some unused java imports
* fixed a bug when comparing `Answer` classes
* added json annotations for setters and getters on the question subclasses
it works tho
---
---
You should probably use `&w=1` because I used a plugin called `Prettier` to format the js, and I reformatted code in the IDE.
I worked off of @bkzhang 's work with `jackson`, and I added json annotations based on the type annotations he added.

Create survey on form submit

---

client/src/components/Survey.js
client/src/components/SurveyList.js
client/src/components/pages/FillSurvey.js
client/yarn.lock
src/main/java/com/example/survey/RestDataConfig.java
src/main/java/com/example/survey/controllers/QuestionController.java
src/main/java/com/example/survey/controllers/SurveyController.java
src/main/java/com/example/survey/models/QuestionRepo.java
src/test/java/com/example/survey/SurveyApplicationTests.java

#61 again
#75 again
This PR adds a QuestionController that handles answering surveys. Included is the frontend functionality of submitting the answers.
Nothing happens after you submit the answers.

Question Controller 3

---

client/src/components/SurveyList.js

Temporary fix for reloading the page when a survey is closed

reload when a survey is closed

---

client/src/components/SurveyList.js

closes #89 
When a survey is closed, remove the option to edit or complete the survey

dont show complete survey or edit survey when survey is closed

---

client/src/components/App.js
client/src/components/EditSurveyForm.js
client/src/components/Survey.js
client/src/components/SurveyList.js
client/src/components/index.js
client/src/components/pages/EditSurvey.js
client/src/components/pages/index.js
client/src/tests/EditSurveyForm.test.js

Closes https://github.com/vikrambombhi/SimpleSurvey/issues/87

Add Edit survey page

---

client/src/components/Survey.js

close #95 
- only send the request when there are no blank answers
- show validation errors on submit attempts with blank answers

Validate Answer Fields

---

client/package.json
client/src/components/App.js
client/src/components/EditSurveyForm.js
client/src/components/SurveyList.js
client/src/components/pages/ReviewSurvey.js
client/src/components/pages/index.js
client/yarn.lock

addresses #72 
- adds a review survey page
- display histogram of range questions
Review by PR for an easier time.

Histogram For Range Questions

---

client/src/components/pages/EditSurvey.js

Fetch the single survey being editted

---

client/src/components/Survey.js

* Fixes survey fill page
* Fixes https://github.com/vikrambombhi/SimpleSurvey/issues/100 by navigating to the surveys page after the survey is filled

Fix ux and fill survey

---

client/src/components/SurveyList.js

view survey results should be viewable when survey is closed

---

client/package.json
client/src/components/SurveyForm.js
client/src/components/pages/NewSurvey.js
client/src/setupTests.js
client/src/tests/NewSurveyModal.test.js
client/yarn.lock

Moved the add question button so that its above the submit button
Closes #88

Move add question button to a more noticeable place
